config/routes.rb
Rails.application.routes.draw do
  resources :itens_carrinho
  resources :carrinhos
  resources :itens
  resources :items
  resources :produtos
  devise_for :usuarios, controllers: { registrations:  'usuarios/registros'  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
  enum status: [:aberto, :finalizado]

  belongs_to :usuario
  has_many :itens_carrinho
  before_save :seta_status, unless: self.status?

  private

  def seta_status
    self.status = :aberto
  end

end

app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
  before_action :set_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /carrinhos
  # GET /carrinhos.json
  def index
    @carrinhos = Carrinho.all
  end

  # GET /carrinhos/1
  # GET /carrinhos/1.json
  def show
  end

  # GET /carrinhos/new
  def new
  end

  # GET /carrinhos/1/edit
  def edit
  end

  # POST /carrinhos
  # POST /carrinhos.json
  def create
    @carrinho = CarrinhoService.new(current_usuario)
    @carrinho.adiciona_item(carrinho_params)

    respond_to do |format|
      if @carrinho.carrinho
        format.json { render json @carrinho.carrinho.to_json }
      else
        format.html { render :new }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrinhos/1
  # PATCH/PUT /carrinhos/1.json
  def update
    respond_to do |format|
      if @carrinho.update(carrinho_params)
        format.html { redirect_to @carrinho, notice: 'Carrinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrinho }
      else
        format.html { render :edit }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrinhos/1
  # DELETE /carrinhos/1.json
  def destroy
    @carrinho.destroy
    respond_to do |format|
      format.html { redirect_to carrinhos_url, notice: 'Carrinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrinho
      @carrinho = Carrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrinho_params
      params.require(:carrinho).permit(:item_id, :qtd)
    end
end

app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

app/views/carrinhos/_form.html.erb
<%= form_with(model: carrinho, local: true) do |form| %>
  <% if carrinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrinho.errors.count, "error") %> prohibited this carrinho from being saved:</h2>

      <ul>
        <% carrinho.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carrinhos/edit.html.erb
<h1>Editing Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Show', @carrinho %> |
<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrinhos</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrinhos.each do |carrinho| %>
      <tr>
        <td><%= carrinho.usuario_id %></td>
        <td><%= link_to 'Show', carrinho %></td>
        <td><%= link_to 'Edit', edit_carrinho_path(carrinho) %></td>
        <td><%= link_to 'Destroy', carrinho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrinho', new_carrinho_path %>

app/views/carrinhos/new.html.erb
<h1>New Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @carrinho.usuario_id %>
</p>

<%= link_to 'Edit', edit_carrinho_path(@carrinho) %> |
<%= link_to 'Back', carrinhos_path %>