config/routes.rb
Rails.application.routes.draw do
  resources :itens_carrinho
  resources :carrinhos
  resources :itens
  resources :items
  resources :produtos
  devise_for :usuarios, controllers: { registrations:  'usuarios/registros'  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/itens_carrinho_controller.rb
class ItensCarrinhoController < ApplicationController
  before_action :set_item_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /itens_carrinho
  # GET /itens_carrinho.json
  def index
    @itens_carrinho = ItemCarrinho.all
  end

  # GET /itens_carrinho/1
  # GET /itens_carrinho/1.json
  def show
  end

  # GET /itens_carrinho/new
  def new
    @item_carrinho = ItemCarrinho.new
  end

  # GET /itens_carrinho/1/edit
  def edit
  end

  # POST /itens_carrinho
  # POST /itens_carrinho.json
  def create
    @item_carrinho = ItemCarrinho.new(item_carrinho_params)

    respond_to do |format|
      if @item_carrinho.save
        format.html { redirect_to @item_carrinho, notice: 'Item carrinho was successfully created.' }
        format.json { render :show, status: :created, location: @item_carrinho }
      else
        format.html { render :new }
        format.json { render json: @item_carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itens_carrinho/1
  # PATCH/PUT /itens_carrinho/1.json
  def update
    respond_to do |format|
      if @item_carrinho.update(item_carrinho_params)
        format.html { redirect_to @item_carrinho, notice: 'Item carrinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_carrinho }
      else
        format.html { render :edit }
        format.json { render json: @item_carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itens_carrinho/1
  # DELETE /itens_carrinho/1.json
  def destroy
    @item_carrinho.destroy
    respond_to do |format|
      format.html { redirect_to itens_carrinho_url, notice: 'Item carrinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_carrinho
      @item_carrinho = ItemCarrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_carrinho_params
      params.require(:item_carrinho).permit(:item_id, :carrinho_id, :qtd_adicionada, :qtd_reservada)
    end
end

app/helpers/itens_carrinho_helper.rb
module ItensCarrinhoHelper
end

app/views/itens_carrinho/_form.html.erb
<%= form_with(model: item_carrinho, local: true) do |form| %>
  <% if item_carrinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_carrinho.errors.count, "error") %> prohibited this item_carrinho from being saved:</h2>

      <ul>
        <% item_carrinho.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :carrinho_id %>
    <%= form.text_field :carrinho_id %>
  </div>

  <div class="field">
    <%= form.label :qtd_adicionada %>
    <%= form.number_field :qtd_adicionada %>
  </div>

  <div class="field">
    <%= form.label :qtd_reservada %>
    <%= form.number_field :qtd_reservada %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/itens_carrinho/edit.html.erb
<h1>Editing Item Carrinho</h1>

<%= render 'form', item_carrinho: @item_carrinho %>

<%= link_to 'Show', @item_carrinho %> |
<%= link_to 'Back', itens_carrinho_path %>

app/views/itens_carrinho/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itens Carrinho</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Carrinho</th>
      <th>Qtd adicionada</th>
      <th>Qtd reservada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itens_carrinho.each do |item_carrinho| %>
      <tr>
        <td><%= item_carrinho.item_id %></td>
        <td><%= item_carrinho.carrinho_id %></td>
        <td><%= item_carrinho.qtd_adicionada %></td>
        <td><%= item_carrinho.qtd_reservada %></td>
        <td><%= link_to 'Show', item_carrinho %></td>
        <td><%= link_to 'Edit', edit_item_carrinho_path(item_carrinho) %></td>
        <td><%= link_to 'Destroy', item_carrinho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Carrinho', new_item_carrinho_path %>

app/views/itens_carrinho/new.html.erb
<h1>New Item Carrinho</h1>

<%= render 'form', item_carrinho: @item_carrinho %>

<%= link_to 'Back', itens_carrinho_path %>

app/views/itens_carrinho/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_carrinho.item_id %>
</p>

<p>
  <strong>Carrinho:</strong>
  <%= @item_carrinho.carrinho_id %>
</p>

<p>
  <strong>Qtd adicionada:</strong>
  <%= @item_carrinho.qtd_adicionada %>
</p>

<p>
  <strong>Qtd reservada:</strong>
  <%= @item_carrinho.qtd_reservada %>
</p>

<%= link_to 'Edit', edit_item_carrinho_path(@item_carrinho) %> |
<%= link_to 'Back', itens_carrinho_path %>