config/routes.rb
Rails.application.routes.draw do
  resources :itens_carrinho
  resources :carrinhos
  resources :itens
  resources :items
  resources :produtos
  devise_for :usuarios, controllers: { registrations:  'usuarios/registros'  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="center">
    STI Corporations ™ - 2019
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <%= link_to "loja virtual", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Início", root_path, class: "navbar-item button" %></li>
          <% if usuario_signed_in? %>
            <li><%= link_to "Meu Carrinho", "#", class: "navbar-item button" %></li>
            <li><%= link_to "Sair", destroy_usuario_session_path, class: "navbar-item" %></li>
          <% else %>
            <li><%= link_to "Entrar", new_usuario_session_path, class: "navbar-item button" %></li>
            <li><%= link_to "Criar conta", new_usuario_registration_path, class: "navbar-item button" %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LojaVirtual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'item', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>

    <% if current_usuario %>
    <div class="carrinho">
      <div >
        <span>0</span> Produtos no carrinho
      </div>
      <ul>
      </ul>
      <div>
        <a href="#0" >Vazio</a>
        <a href="#0">Finalizar - <span>R$0</span></a>
      </div>
    </div>
    <% end  %>

    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>